import type { ItemPreviewSchema } from '@/types/item-controller';

export const ITEM_LIST: ItemPreviewSchema[] = [
  {
    itemId: 1001,
    itemName: '상품명 1줄',
    itemDescription: '',
    price: 10000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1002,
    itemName: '상품명 2줄 상품명 2줄 상품명 2줄 상품명 2줄',
    itemDescription: '',
    price: 10000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1003,
    itemName: '상품명 3줄 이상 상품명 3줄 이상 상품명 3줄 이상 상품명 3줄 이상',
    itemDescription: '',
    price: 10000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1101,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1102,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1103,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1104,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1105,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1106,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1107,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1108,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1109,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1110,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1111,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1112,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1113,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1114,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1115,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1116,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1117,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1118,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1119,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1120,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1121,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1122,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1123,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1124,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1125,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1126,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1127,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1128,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1129,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1130,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1131,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1132,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1133,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1134,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1135,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1136,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1137,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1138,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1139,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1140,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1141,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1142,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1143,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1144,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1145,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1146,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1147,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1148,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1149,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1150,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1201,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1202,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1203,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1204,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1205,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1206,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1207,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1208,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1209,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1210,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1211,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1212,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1213,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1214,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1215,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1216,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1217,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1218,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1219,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1220,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1221,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1222,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1223,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1224,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1225,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1226,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1227,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1228,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1229,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1230,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1231,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1232,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1233,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1234,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1235,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1236,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1237,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1238,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1239,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1240,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1241,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1242,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1243,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1244,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1245,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1246,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1247,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1248,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1249,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1250,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1301,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1302,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1303,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1304,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1305,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1306,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1307,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1308,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1309,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1310,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1311,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1312,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1313,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1314,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1315,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1316,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1317,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1318,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1319,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1320,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1321,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1322,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1323,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1324,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1325,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1326,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1327,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1328,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1329,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1330,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1331,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1332,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1333,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1334,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1335,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1336,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1337,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1338,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1339,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1340,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1341,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1342,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1343,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1344,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1345,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1346,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1347,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1348,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1349,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1350,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1401,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1402,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1403,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1404,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1405,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1406,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1407,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1408,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1409,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1410,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1411,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1412,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1413,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1414,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1415,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1416,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1417,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1418,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1419,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1420,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1421,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1422,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1423,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1424,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1425,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1426,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1427,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1428,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1429,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1430,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1431,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1432,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1433,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1434,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1435,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1436,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1437,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1438,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1439,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1440,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1441,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1442,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1443,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1444,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1445,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1446,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1447,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1448,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1449,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1450,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1501,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1502,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1503,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1504,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1505,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1506,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1507,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1508,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1509,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1510,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1511,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1512,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1513,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1514,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1515,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1516,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1517,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1518,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1519,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1520,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1521,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1522,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1523,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1524,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1525,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1526,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1527,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1528,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1529,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1530,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1531,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1532,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1533,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1534,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1535,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1536,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1537,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1538,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1539,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1540,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1541,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1542,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1543,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1544,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1545,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1546,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1547,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1548,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1549,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1550,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1601,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16010,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1602,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16020,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1603,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16030,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1604,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16040,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1605,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16050,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1606,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16060,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1607,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16070,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1608,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16080,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1609,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16090,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1610,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16100,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1611,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16110,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1612,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16120,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1613,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16130,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1614,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16140,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1615,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16150,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1616,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16160,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1617,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16170,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1618,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16180,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1619,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16190,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1620,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16200,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1621,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16210,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1622,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16220,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1623,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16230,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1624,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16240,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1625,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16250,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1626,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16260,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1627,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16270,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1628,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16280,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1629,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16290,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1630,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16300,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1631,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16310,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1632,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16320,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1633,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16330,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1634,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16340,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1635,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16350,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1636,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16360,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1637,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16370,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1638,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16380,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1639,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16390,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1640,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16400,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1641,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16410,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1642,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16420,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1643,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16430,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1644,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16440,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1645,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16450,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1646,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16460,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1647,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16470,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1648,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16480,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1649,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16490,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1650,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16500,
    thumbnailUrl: '',
    artistId: 2,
    artistName: '아티스트',
    isWished: false,
  },
  // Artist
  {
    itemId: 1160,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1161,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1162,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1163,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1164,
    itemName: '아름다운 컵/잔',
    itemDescription: '',
    price: 11640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1260,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1261,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1262,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1263,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1264,
    itemName: '아름다운 그릇/사기',
    itemDescription: '',
    price: 12640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1360,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1361,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1362,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1363,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1364,
    itemName: '아름다운 커피/티용품',
    itemDescription: '',
    price: 13640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1460,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1461,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1462,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1463,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1464,
    itemName: '아름다운 화병',
    itemDescription: '',
    price: 14640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1560,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1561,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1562,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1563,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1564,
    itemName: '아름다운 오브제',
    itemDescription: '',
    price: 15640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1660,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16600,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1661,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16610,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1662,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16620,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1663,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16630,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  {
    itemId: 1664,
    itemName: '아름다운 기타',
    itemDescription: '',
    price: 16640,
    thumbnailUrl: '',
    artistId: 3,
    artistName: '박아름',
    isWished: false,
  },
  // Thumbnail
  {
    itemId: 1801,
    itemName: '첫 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1802,
    itemName: '두 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1803,
    itemName: '세 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1804,
    itemName: '네 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1805,
    itemName: '다섯 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  // Now Popular
  {
    itemId: 1901,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1902,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1903,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1904,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
  {
    itemId: 1905,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistId: 1,
    artistName: '아티스트',
    isWished: false,
  },
];
