import type { Item } from '@/types/item.dto';

export const ITEM_LIST: Item[] = [
  // Thumbnail
  {
    itemId: 1801,
    itemName: '첫 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistName: 'NONE',
    isWished: false,
    sale: 0,
  },
  {
    itemId: 1802,
    itemName: '두 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistName: 'NONE',
    isWished: false,
    sale: 0,
  },
  {
    itemId: 1803,
    itemName: '세 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistName: 'NONE',
    isWished: false,
    sale: 0,
  },
  {
    itemId: 1804,
    itemName: '네 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistName: 'NONE',
    isWished: false,
    sale: 0,
  },
  {
    itemId: 1805,
    itemName: '다섯 번째',
    itemDescription: '',
    price: 0,
    thumbnailUrl: '',
    artistName: 'NONE',
    isWished: false,
    sale: 0,
  },
  // Now Popular
  {
    itemId: 1901,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistName: '아티스트',
    isWished: false,
    sale: 30,
  },
  {
    itemId: 1902,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistName: '아티스트',
    isWished: false,
    sale: 30,
  },
  {
    itemId: 1903,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistName: '아티스트',
    isWished: false,
    sale: 30,
  },
  {
    itemId: 1904,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistName: '아티스트',
    isWished: false,
    sale: 30,
  },
  {
    itemId: 1905,
    itemName: '반짝반짝 도자기',
    itemDescription: '',
    price: 28000,
    thumbnailUrl: '',
    artistName: '아티스트',
    isWished: false,
    sale: 30,
  },
];
