import type { Review } from '@/types/review.dto';

export const REVIEW_LIST: Review[] = [
  {
    nickname: '햇살가득',
    rating: 1,
    date: '2025-05-07',
    description: '사진보다 실물이 훨씬 고급스럽네요. 만족합니다!',
    images: ['/src/image/review-image1.jpg', '/src/image/review-image2.jpg'],
  },
  {
    nickname: '블루밍데이',
    rating: 5,
    date: '2025-06-15',
    description: '포장이 좀 허술해서 별점 낮춥니다. 제품은 무난했어요.',
    images: ['/src/image/review-image3.jpg'],
  },
  {
    nickname: '쿠쿠루삥뽕',
    rating: 4,
    date: '2025-06-09',
    description: '기대했던 것보단 작지만 디자인이 예뻐서 만족해요.',
    images: ['/src/image/review-image4.jpg'],
  },
  {
    nickname: '초코푸딩',
    rating: 4,
    date: '2025-06-16',
    description: '생각보다 빨리 도착했고 사용법도 쉬워요. 만족!',
    images: ['/src/image/review-image5.jpg'],
  },
  {
    nickname: '민트초코러버',
    rating: 1,
    date: '2025-03-10',
    description: '평범한 제품이에요. 특별히 좋거나 나쁘진 않네요.',
    images: ['/src/image/review-image6.jpg', '/src/image/review-image7.jpg', '/src/image/review-image8.jpg'],
  },
  {
    nickname: '밤하늘별빛',
    rating: 5,
    date: '2025-05-12',
    description: '사진보다 실물이 훨씬 고급스럽네요. 만족합니다!',
    images: ['/src/image/review-image9.jpg'],
  },
  {
    nickname: '냥냥펀치',
    rating: 3,
    date: '2025-06-13',
    description: '가성비 최고예요. 만족합니다!',
    images: ['/src/image/review-image10.jpg', '/src/image/review-image11.jpg', '/src/image/review-image12.jpg'],
  },
  {
    nickname: '로지',
    rating: 3,
    date: '2025-06-09',
    description: '깔끔하고 실용적이에요. 재구매 의사 있어요!',
    images: ['/src/image/review-image13.jpg', '/src/image/review-image14.jpg', '/src/image/review-image15.jpg'],
  },
  {
    nickname: '진진자라',
    rating: 5,
    date: '2025-03-13',
    description: '가성비 최고예요. 만족합니다!',
    images: ['/src/image/review-image16.jpg', '/src/image/review-image17.jpg'],
  },
  {
    nickname: '하늘보리',
    rating: 5,
    date: '2025-05-30',
    description: '친구 추천으로 샀는데 대만족입니다! 또 사고 싶어요.',
    images: ['/src/image/review-image18.jpg', '/src/image/review-image19.jpg'],
  },
  {
    nickname: '도란도란',
    rating: 3,
    date: '2025-04-16',
    description: '배송도 빠르고 제품도 튼튼해요. 선물용으로도 좋을 것 같아요!',
    images: [],
  },
  {
    nickname: '감자칩러버',
    rating: 2,
    date: '2025-04-16',
    description: '기대했던 것보단 작지만 디자인이 예뻐서 만족해요.',
    images: [],
  },
  {
    nickname: '피치베어',
    rating: 3,
    date: '2025-03-19',
    description: '사진보다 실물이 훨씬 고급스럽네요. 만족합니다!',
    images: ['/src/image/review-image20.jpg'],
  },
  {
    nickname: '자몽청',
    rating: 4,
    date: '2025-06-17',
    description: '배송도 빠르고 제품도 튼튼해요. 선물용으로도 좋을 것 같아요!',
    images: [],
  },
  {
    nickname: '마시멜로우',
    rating: 2,
    date: '2025-06-22',
    description: '생각보다 빨리 도착했고 사용법도 쉬워요. 만족!',
    images: [],
  },
  {
    nickname: '러브송',
    rating: 1,
    date: '2025-03-03',
    description: '포장이 좀 허술해서 별점 낮춥니다. 제품은 무난했어요.',
    images: ['/src/image/review-image21.jpg'],
  },
  {
    nickname: '스노우볼',
    rating: 2,
    date: '2025-03-05',
    description: '평범한 제품이에요. 특별히 좋거나 나쁘진 않네요.',
    images: ['/src/image/review-image22.jpg'],
  },
  {
    nickname: '달콤새콤',
    rating: 2,
    date: '2025-04-10',
    description: '중간 정도의 퀄리티에요. 가격 생각하면 괜찮은 듯.',
    images: ['/src/image/review-image23.jpg'],
  },
  {
    nickname: '별빛초코',
    rating: 4,
    date: '2025-05-03',
    description: '포장이 좀 허술해서 별점 낮춥니다. 제품은 무난했어요.',
    images: ['/src/image/review-image24.jpg', '/src/image/review-image25.jpg', '/src/image/review-image26.jpg'],
  },
  {
    nickname: '유자소다',
    rating: 5,
    date: '2025-06-02',
    description: '생각보다 빨리 도착했고 사용법도 쉬워요. 만족!',
    images: ['/src/image/review-image27.jpg', '/src/image/review-image28.jpg'],
  },
  {
    nickname: '해피캣',
    rating: 2,
    date: '2025-04-22',
    description: '깔끔하고 실용적이에요. 재구매 의사 있어요!',
    images: ['/src/image/review-image29.jpg', '/src/image/review-image30.jpg'],
  },
  {
    nickname: '푸른숲',
    rating: 1,
    date: '2025-05-26',
    description: '소재가 부드럽고 마감도 잘 되어있어요.',
    images: ['/src/image/review-image31.jpg', '/src/image/review-image32.jpg', '/src/image/review-image33.jpg'],
  },
  {
    nickname: '멜로우타임',
    rating: 2,
    date: '2025-05-12',
    description: '사진이랑 거의 똑같아요. 맘에 들어요.',
    images: ['/src/image/review-image34.jpg', '/src/image/review-image35.jpg', '/src/image/review-image36.jpg'],
  },
  {
    nickname: '꿀벌이',
    rating: 5,
    date: '2025-03-17',
    description: '생각보다 빨리 도착했고 사용법도 쉬워요. 만족!',
    images: ['/src/image/review-image37.jpg'],
  },
  {
    nickname: '작은별',
    rating: 2,
    date: '2025-06-25',
    description: '기대했던 것보단 작지만 디자인이 예뻐서 만족해요.',
    images: ['/src/image/review-image38.jpg'],
  },
  {
    nickname: '보름달밤',
    rating: 4,
    date: '2025-05-31',
    description: '가성비 최고예요. 만족합니다!',
    images: ['/src/image/review-image39.jpg', '/src/image/review-image40.jpg', '/src/image/review-image41.jpg'],
  },
  {
    nickname: '솜사탕빛',
    rating: 1,
    date: '2025-03-08',
    description: '가성비 최고예요. 만족합니다!',
    images: [],
  },
  {
    nickname: '베리굿',
    rating: 4,
    date: '2025-05-13',
    description: '배송도 빠르고 제품도 튼튼해요. 선물용으로도 좋을 것 같아요!',
    images: ['/src/image/review-image42.jpg', '/src/image/review-image43.jpg'],
  },
  {
    nickname: '새벽달',
    rating: 2,
    date: '2025-03-06',
    description: '평범한 제품이에요. 특별히 좋거나 나쁘진 않네요.',
    images: [],
  },
  {
    nickname: '몽글몽글',
    rating: 5,
    date: '2025-05-10',
    description: '생각보다 더 튼튼해서 놀랐어요!',
    images: ['/src/image/review-image44.jpg'],
  },
];
